### PR TITLE
Implement support for arcs

### LINKED ISSUE #19: Support arcs as well as Bezier curves
The current implementation doesn't support arcs ("Unsupported path segment: EllipticalArc"), something that's required by my application :-(

### PR DESCRIPTION
**Pull request by Perondas**
Fixes #19

Converts the acr into Bézier curves.
Solution taken from [here](https://github.com/BigBadaboom/androidsvg)

### CODE REVIEW

**Comment by Perondas** [comment]
Converts this: 
arcs
Into this:
image

**Comment by dbrgn** [comment]
Awesome! I'll try to look into it in the coming days. If I forget about it, feel free to ping me.

**Comment by Perondas** [comment]
@dbrgn did you have any time to look it over?

**Comment by Perondas** [comment]
@dbrgn I was looking trough my PRs and noticed that this one was never merged. Any specific reason for that or is this simply a low priority repo?

**Comment by dbrgn** [comment]
Thanks for the reminder. No specific reason, just a high workload in general 🙂 I'll put it on top of my TODO-list again!

**Comment by dbrgn** [comment]
@Perondas I pushed a commit that does a little cleanup and fixes the clippy lints on WARNING level. Thank you for this contribution!

**Pull request merged**
